### ISSUE TITLE
feat: objectMode

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/to-readable-stream#2]
I'm hoping to contribute this feature (unless of course, it's unwanted), so creating an issue for tracking and discussion. I would very much like to see this module support streaming of objects, and thus leveraging the `objectMode` option.

**Comment by sindresorhus** [comment]
Sure, as long as it doesn't require a lot of code.

**Comment by shellscape** [comment]
I've spent some time with this and it seems that it either handles a myriad of use-cases, or there isn't any value there. And with that, it seems more prudent _not_ to use a convenience wrapper, as `objectMode` requires fine tuning that doesn't suit a wrapper.

Going to let this marinate for a bit longer before I close.

**Comment by sindresorhus** [comment]
Closing as this exists in https://github.com/sindresorhus/into-stream#intostreamobjectinput
