### ISSUE TITLE
Use `stream.Readable.from`

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/to-readable-stream#6]
`stream.Readable.from` was added in Node.js v12.3.0 and v10.17.0, allowing for easier conversion to Readable Streams:

```js
const {Readable} = require('stream');

Readable.from('🦄🌈').pipe(process.stdout);
```

As well as this, it also supports generator functions:

```js
const {Readable} = require('stream');

async function * generate() {
  yield '🦄';
  yield '🌈';
}

Readable.from(generate()).pipe(process.stdout);
```

Perhaps we could utilise this here?

// @sindresorhus

**Comment by sindresorhus** [comment]
Doesn't that API make this package moot?

**Comment by Richienb** [comment]
@sindresorhus It does. We should either backport the generator function support or link to the API and deprecate this package.

**Comment by sindresorhus** [comment]
It's not feasible to use that API for Node.js 10 projects, since it's a recent addition, and from experience, no one updates Node.js minor versions. I have added a note in the readme about Node.js 12. I'll deprecate this package sometime in the future when Node.js 10 is obsolete.

**Comment by Richienb** [comment]
> I'll deprecate this package sometime in the future when Node.js 10 is obsolete

Node.js 10 End of life: 30 April 2021
